print(1)
raise ValueError("Mensagem de erro")
